// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2pJ6fU0Rmdtwgok0qAwtfUx-Fnr96pkA',
    appId: '1:66667199442:web:0092f17e2e82759b59260b',
    messagingSenderId: '66667199442',
    projectId: 'fitnessfit-20776',
    authDomain: 'fitnessfit-20776.firebaseapp.com',
    storageBucket: 'fitnessfit-20776.firebasestorage.app',
    measurementId: 'G-TGF5SJQ30J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdETTdiKVRilV2kdGIBCxqpDPWrN1GJ1I',
    appId: '1:66667199442:android:edacabe85a5f407659260b',
    messagingSenderId: '66667199442',
    projectId: 'fitnessfit-20776',
    storageBucket: 'fitnessfit-20776.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRhhRj1YhzRIPyyoYAMZKzhXcvXQsFtL8',
    appId: '1:66667199442:ios:126765f64e51adbd59260b',
    messagingSenderId: '66667199442',
    projectId: 'fitnessfit-20776',
    storageBucket: 'fitnessfit-20776.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRhhRj1YhzRIPyyoYAMZKzhXcvXQsFtL8',
    appId: '1:66667199442:ios:126765f64e51adbd59260b',
    messagingSenderId: '66667199442',
    projectId: 'fitnessfit-20776',
    storageBucket: 'fitnessfit-20776.firebasestorage.app',
    iosBundleId: 'com.example.fitnessFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2pJ6fU0Rmdtwgok0qAwtfUx-Fnr96pkA',
    appId: '1:66667199442:web:e650cf94700c11a359260b',
    messagingSenderId: '66667199442',
    projectId: 'fitnessfit-20776',
    authDomain: 'fitnessfit-20776.firebaseapp.com',
    storageBucket: 'fitnessfit-20776.firebasestorage.app',
    measurementId: 'G-CEX5RGC38N',
  );
}
